base/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.routes),
    path('usuarios/', views.usuarios),
    path('usuario/<int:id>', views.user),
    path('pagos/<int:id>', views.pagos),
    path('posts/<str:usuario>', views.posts),
]

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/',views.register_page),
    path('login/',views.login_page),
    path('',views.home),
    path('soport/', views.soport_page),
    path('logout/',views.logout_page),
    path('comment/',views.publications),
    path('publish/',views.posts),
    path('megusta/', views.like),
    path('comentario/', views.comentar),
    path('pay/',views.pay),
]

cheep/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('',include('base.urls')),
    path ('api/', include('base.api.urls'))
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    text= models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    def __str__(self):
        return self.text

class Comment(models.Model):
    text= models.TextField()
    post=models.ForeignKey(Post, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    def __str__(self):
        return self.text
    
class Soport(models.Model):
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    email = models.EmailField()

class Like(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

class Payment(models.Model):
    user= models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)
    bank = models.CharField(max_length=20)
    account_number = models.IntegerField()
    page = models.CharField(max_length=20)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

base/api/views.py
from django.http import JsonResponse
from ..models import Post, Comment, Like, Payment
from django.contrib.auth.models import User

def routes(request):
    routes = [
        'GET /api/usuarios',
        'GET /api/usuario/id',
        'GET /api/posts/usuario',
        'GET /api/pagos/id',
    ]
    return JsonResponse(routes, safe=False)

def usuarios(request):
    usuarios= User.objects.all()
    data = []
    for usuario in usuarios:
        data.append({
            'username': usuario.username,
            'first_name': usuario.first_name,
            'last_name' : usuario.last_name,
            'email': usuario.email
        })

    return JsonResponse(data, safe=False)
    
def user(request,id):
    user = User.objects.get(id=id)
    user_dict = {
        'username': user.username,
            'first_name': user.first_name,
            'last_name' : user.last_name,
            'email': user.email
    }
    return JsonResponse(user_dict, safe=False)

def posts(request, usuario):
    data=[]
    id = User.objects.get(username=usuario)
    posts = Post.objects.filter(user=id)
    for post in posts:
        comentariosData = []
        comentarios = Comment.objects.filter(post=post)
        for comentario in comentarios:
            comentariosData.append({
                'username': comentario.user.username,
                'text': comentario.text
            })
        megustasData =[]
        megustas = Like.objects.filter(post=post)
        for megusta in megustas:
            megustasData.append({
                'username': megusta.user.username,
            })
        data.append({
            'username' : id.username,
            'text': post.text,
            'comentarios': comentariosData,
            'megustas': megustasData
        })
    return JsonResponse(data, safe=False)

def pagos(request,id):
    pagos = Payment.objects.get(id=id)
    pagos_dict= {
        'username': pagos.user.username,
        'banco': pagos.bank,
        'numero' : pagos.account_number,
        'montoTotal': pagos.amount
    }
    return JsonResponse(pagos_dict, safe=False)

base/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import Post, Soport, Like, Comment, Payment

# Create your views here.

def register_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        if password != confirm_password:
            messages.error(request,'Las contraseñas no coinciden')
            return redirect('/register')
        User.objects.create_user(username, email=email, first_name=first_name, last_name=last_name, password=password)
        return redirect('/login')
    return render (request, 'register_page.html')
        
def login_page(request):
    if (request.method == 'POST'):
        username= request.POST.get('username')
        password= request.POST.get('password')
        if User.objects.filter(username=username).exists():
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Se inició sesión correctamente')
                return redirect('/')
        messages.success(request, 'Datos incorrectos')
    return render(request,'login.html')

def home(request):
    return render(request, 'home.html')

def soport_page(request):
    if (request.method == 'POST'):
        email = request.POST.get('email')
        sugerencia = request.POST.get('sugerencia')
        Soport.objects.create(text = sugerencia, email = email)
        messages.success(request, 'Se envio la sugerencia')
    return render (request,'soport.html')

def logout_page(request):
    logout(request)
    return redirect ('/login/')

def publications(request):
    usuario = User.objects.get(username=request.user)
    posts= Post.objects.all().order_by('-created')

    if len(posts) == 0: posts = None
    data = {'usuario':usuario, 'posts': posts}   
    return render (request,'comment.html', data)

def posts(request):
    id = request.POST.get('id')
    text = request.POST.get('text')
    if(id is None and text !=''):
        Post.objects.create(text = text,user = request.user)
        messages.success(request, 'Post creado correctamente')
    return redirect('/comment/')

def like(request):
    usuario = User.objects.get(username=request.user)
    pId = request.POST.get('megusta')
    post = Post.objects.get(id=pId)
    try:
        comprobar = Like.objects.get(user= usuario, post= post)
        comprobar.delete()
        print("borrar")
    except:
        Like.objects.create(user = request.user,post = post)
        print("hola")
    return redirect('/comment/')

def comentar(request):
    p = Post.objects.get(id = request.POST.get('post'))
    Comment.objects.create(
        text = request.POST.get('text'),
        user = request.user,
        post = p
    )
    return redirect('/comment/')

def pay(request):
    if request.method == 'POST':
        bank = request.POST.get('bank')
        account_number = request.POST.get('account_number')
        page = request.POST.get('page')
        amount = request.POST.get('amount')
        user = request.user
        
        if bank == '' or account_number == '' or page == '' or amount == '':
            messages.error(request, 'Rellene todos los espacios')
            return redirect('/pay/')  # Redirige a la página 'pay.html'
        else:
            Payment.objects.create(bank=bank, account_number=account_number, page=page, user=user, amount=amount)
            messages.success(request, 'Solicitud de pago generada correctamente')
            return redirect('/')  # Redirige a la página 'pay.html'
    
    return render(request, 'pay.html')

base/templates/comment.html
{% extends "layouts/main.html" %}
{% load static %}

{% block content %}
<style>
    .custom-card {
        background: linear-gradient(to right, #613523fa, #3b1c3bd3, #613523fa);
        color: white;
    }
    .border-card {
        border-width: 2px; /* Ajusta el grosor del borde según tus necesidades */
        border-style: solid;
    }
    .custom-button {
        background-color: #613523fa; /* Cambia el color de fondo según tus necesidades */
        color: #ffffff; /* Cambia el color del texto según tus necesidades */
        /* Otros estilos de tu elección */
    }
</style>
<form class="card custom-card p-2" method="POST" action="/publish/">
    <h1>Deja tu comentario sobre nosotros</h1>
    {% csrf_token %}
    <div class="form-group my-3 ">
        <textarea class="form-control form-control-sm" placeholder="Escribe un comentario" name="text">{% if post is not None %}{{post.text}}{% endif %}</textarea>
    </div>
    <div class="text">
        <button class="btn btn-light" type="submit">Publicar</button>
    </div>
</form>
<br/>
{% if posts == None %}
<h1>No hay publicaciones</h1>
{% endif %}

{% for p in posts %}
<div class="card border-card p-3 ">
    <div class="row d-flex align-items-center justify-content-center">
        <img class="col-lg-1 col-6"src="{% static 'images/models.png' %}" alt="mi imagen" style="border-radius: 50%; width: 100px; height: 80px;">
        <h4 class="col-lg-3 col-6">{{p.user}} comentó: </h4>
        <h5 class="col-lg-6 col-12">{{p.text}}</h5>        
    </div>
    <br/>
    <div class="row d-flex align-items-center justify-content-center">
        <div class="col-1">
            <form method="POST" action="/megusta/">
                {% csrf_token %}
                <input type="hidden" value="{{p.id}}" name="megusta">
                <button class="btn btn-primary custom-button" type="submit">❤️</button>
            </form>
        </div>
        <div class="col-11">
            <span><b>Le gusta a:</b> </span>
            {% for m in p.like_set.all %}
            <span>{{m.user}} </span>

            {% endfor %}
        </div>
    </div>
    <p>{{p.created}}</p>
    <br/>
    <div class="">
        <div class="px-3">
            {% if request.user.is_superuser %}
            <form method="POST" action="/comentario/">
                {% csrf_token %}
                <input type="hidden" value="{{p.id}}" name="post">
                <div class="form-group">
                    <textarea class="form-control" name="text" placeholder="Comenta la publicación anterior"></textarea>
                </div>
                <button class="btn btn-secondary" type="submit">Enviar comentario</button>
            </form>
            {% endif %}
        </div>
    </div>
    <br/>
    <h5>Comentarios:</h5>
    {% for c in p.comment_set.all %}
        <div class="p-3">
            <div class="card px-3">
                <p><b>{{c.user}}</b>: {{ c.text }}</p>
                <p>{{c.created}} </p>
            </div>
        </div>
    {% endfor %}
</div>

{% endfor %}
{% endblock %}

base/templates/home.html
{% extends "layouts/main.html" %}
{% block content %}
<style>
    .custom-card {
        background: linear-gradient(to right, #613523fa, #3b1c3bd3, #613523fa);
        color: white;
        font-size: 25px;
        text-align: center;
    }
</style>

<div class="text-center">
    <h1>Bienvenido {{user}} a la página de OlimpoWeb</h1>
</div>

<div class="row d-flex align-items-center justify-content-center py-5 ">
    <div class="col-lg-3 col-12 card m-2 custom-card">¿Quieres ganar más dinero con nosotros y posicionarte adecuadamente?</div>
    <div class="col-lg-3 col-12 card m-3 custom-card">¿Trabajas en un studio fisico y se te quedan con aproximadamente la mitad de tus ganancias y además, no te brindan ya ayuda porque tienes buena experiencia?</div>
    <div class="col-lg-3 col-12 card m-3 custom-card">Tienes tu computadora, camara y un espacio para trabajar...</div>
</div>
{% endblock %}

base/templates/layouts/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>Mi página</title>
    <style>
        .navbar {
            background: linear-gradient(to right, #613523fa, #3b1c3b80, #6135238f);
        }

        .navbar-nav .nav-link {
            color: white;
        }

    </style>
</head>

<body>
    <header>
        <nav class="row navbar navbar-expand-md navbar-dark fixed-top bg-dark ">
            <div class="row d-flex align-items-center justify-content-center">
                <img class="col-lg-4 col-12" src="{% static 'images/Titulob.png' %}" alt="mi imagen" style=" width: 250px; height: 80px;">
                
                <div class="col-lg-6 col-12 collapse navbar-collapse d-flex align-items-center justify-content-center" id="navbarCollapse">
                    <ul class="row navbar-nav mr-auto ">
                        {% if request.user.is_authenticated%}
                        <li class="col-lg-1 col-12 nav-item active d-flex align-items-center justify-content-center">
                            <a class="nav-link" href="/">Inicio</a>
                        </li>
                        <li class="col-lg-3 col-12 nav-item d-flex align-items-center justify-content-center">
                            <a class="nav-link" href="/pay">Solicitud de dinero</a>
                        </li>
                        
                        <li class="col-lg-2 nav-item d-flex align-items-center justify-content-center">
                            <a class="nav-link" href="/comment">Comentarios</a>
                        </li>
                        {% endif %}
                        <li class="col-lg-2 nav-item m-3 d-flex align-items-center justify-content-center">
                            <a class="nav-link" href="/soport">Soporte</a>
                        </li>
    
                        {% if request.user.is_authenticated%}
                        <li class="col-lg-3 nav-item d-flex align-items-center justify-content-center">
                            <a class="nav-link" href="/logout">Cerrar sesión</a>
                        </li>
                        {% else %}
                        <li class="col-lg-3 nav-item d-flex align-items-center justify-content-center">
                            <a class="nav-link" href="/login">Iniciar sesión</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container my-5">

        <div class='p-lg-5 p-5 '></div>
        <div class='p-lg-0 p-5 '></div>
        <div class='p-lg-0 p-4 '></div>

        <div class="py-4">
            {% if messages %}
                {% for message in messages %}
                    {{ message.tags }} 
                    <div class="alert alert-success" role="alert">
                        {{message}}
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        <div id="content">
            {% block content %}
        
            {% endblock %}
        </div>
          
    </main>
    <footer class="footer bg-light p-4 fixed-bottom">
        <div class="container">
            <span class="text-muted">Curso de Django para Lumetrio.com</span>
        </div>
    </footer> 
</body>
</html>

base/templates/login.html
{% extends "layouts/main.html" %}

{% load static %}

{% block content %}

<style>
    .custom-card {
        background: linear-gradient(to right, #613523fa, #3b1c3bd3, #613523fa);
        color: white;
    }
</style>

<form class="card p-4 shadow-lg custom-card" method="POST" action="">
    <div class="d-flex align-items-center justify-content-center">
        <img src="{% static 'images/LOGO1.png' %}" alt="Logo" style="width: 150px; height: 150px;">
        <h1>Iniciar Sesión</h1>
    </div>
    
    {% csrf_token %}
    <div class="form-group my-3">
        <label>Usuario</label>
        <input type="text" class="form-control" name="username" placeholder="Nombre de usuario">
        
    </div>
    <div class="form-group my-3">
        <label>Contraseña</label>
        <input type="password" class="form-control" name="password" placeholder="Contraseña">
    </div>
    <div>

        <a href="/register">Aún no tengo cuenta</a>
    </div>
    <div class="text-center">

        <button class="btn btn-light" type="submit">Iniciar Sesión</button>
    </div>
</form>
{% endblock %}

base/templates/pay.html
{% extends "layouts/main.html" %}
{% load static %}
{% block content %}

<style>
    .custom-card {
        background: linear-gradient(to right, #613523fa, #3b1c3bd3, #613523fa);
        color: white;
    }
</style>

<form class="card custom-card p-5" method="POST" action="">
    <div class="d-flex align-items-center justify-content-center">
        <img src="{% static 'images/pagos.png' %}" alt="mi imagen" style=" width: 200px; height: 150px;">
        <h1 class="text-center">Solicitud de pago</h1>
    </div>
    {% csrf_token %}
    <div class="form-group my-3">
        <label>Banco</label>
        <input type="text" class="form-control" name="bank" placeholder="Escriba su banco">
    </div>

    <div class="form-group my-3">
        <label>Número de cuenta</label>
        <input type="number" class="form-control" name="account_number" placeholder="Escriba número de cuenta">
    </div>

    <div class="form-group my-3">
        <label>Página</label>
        <input type="text" class="form-control" name="page" placeholder="Página">
    </div>

    <div class="form-group my-3">
        <label>Monto</label>
        <input type="number" class="form-control" name="amount" placeholder="Monto total">
    </div>
    <div class="text-center">

        <button class="btn btn-light" type="submit">Enviar</button>
    </div>
</form>
{% endblock %}

base/templates/register_page.html
{% extends "layouts/main.html" %}
{% load static %}
{% block content %}

<style>
    .custom-card {
        background: linear-gradient(to right, #613523fa, #3b1c3bd3, #613523fa);
        color: white;
    }
</style>

<form class="card custom-card p-5" method="POST" action="">
    <div class="d-flex align-items-center justify-content-center">
        <img src="{% static 'images/registro.png' %}" alt="mi imagen" style=" width: 200px; height: 150px;">
        <h1 class="text-center">Registro</h1>
    </div>
    {% csrf_token %}
    <div class="form-group my-3">
        <label>Usuario</label>
        <input type="text" class="form-control" name="username" placeholder="Nombre de usuario">
    </div>

    <div class="form-group my-3">
        <label>email</label>
        <input type="email" class="form-control" name="email" placeholder="Email">
    </div>

    <div class="form-group my-3">
        <label>Nombre</label>
        <input type="text" class="form-control" name="first_name" placeholder="Nombre">
    </div>

    <div class="form-group my-3">
        <label>Apellido</label>
        <input type="text" class="form-control" name="last_name" placeholder="Apellido">
    </div>

    <div class="form-group my-3">
        <label>Contraseña</label>
        <input type="password" class="form-control" name="password" placeholder="Contraseña">
    </div>

    <div class="form-group my-3">
        <label>Confirmar contraseña</label>
        <input type="password" class="form-control" name="confirm_password" placeholder="Confirmar contraseña">
    </div>
    <div class="text-center">

        <button class="btn btn-light" type="submit">Registro</button>
    </div>
</form>
{% endblock %}

base/templates/soport.html
{% extends "layouts/main.html" %}
{% load static %}

{% block content %}
<style>
    .custom-card {
        background: linear-gradient(to right, #613523fa, #3b1c3bd3, #613523fa);
        color: white;
    }

</style>
<br/>
<label><b>Envíanos un mensaje y uno de nuestros operadores se pondrá en contacto contigo</b></label>
<br/>
<br/>
<div class="card p-3 row shadow-lg custom-card text-light">
    <h1 class="text-center">Soporte</h1>
    <div class="row ">
        <div class="col-lg-4 col-12 d-flex align-items-center justify-content-center">
            <img src="{% static 'images/soporte.png' %}" alt="mi imagen" style=" width: 200px; height: 150px;">
        </div>
        <div class="col-lg-7 col-12 d-flex align-items-center justify-content-center">
            <form method="POST" action="">
                {% csrf_token %}
        
                <div class="form-group my-3">
                    <label>Email</label>
                    <input type="email" class="form-control" name="email" placeholder="Email">
                </div>
        
                <div class="form-group my-3">
                    <label>Sugerencia</label>
                    <input type="text" class="form-control" name="sugerencia" placeholder="sugerencia">
                </div>
                <button class="btn btn-light" type="submit">Enviar</button>
            </form>
        </div>
    </div>
    
</div>

{% endblock %}